### PR TITLE
new thumbnail template added

### PR DESCRIPTION
**Pull request by zainbinfurqan**
seo 2
seo

### CODE REVIEW

**Comment by AhsanAyaz** [comment]
@zainbinfurqan the text looks super small for the title. It will be very difficult to read on mobile screens.
Can you make the font-size at least equal to what we have for my name? Please update the screenshots here as well.

**Comment by zainbinfurqan** [comment]
> @zainbinfurqan the text looks super small for the title. It will be very difficult to read on mobile screens.
> Can you make the font-size at least equal to what we have for my name? Please update the screenshots here as well.

Yup sure.

**Comment by zainbinfurqan** [comment]
@AhsanAyaz   as per library the max font size can be FONT_SANS_128_BLACK, which it's already using in application, Do you have any idea how i can increase it, I tried to find out a solution but it will required to add custom font.

**Comment by zainbinfurqan** [comment]
seo
seo

**Comment by zainbinfurqan** [comment]
@AhsanAyaz  Here is updated image and font size

**Pull request merged**
